# Generated by Django 5.1 on 2025-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('id_contenido', models.IntegerField()),
                ('tipo_contenido', models.CharField(max_length=50)),
                ('fecha_visualizacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
    ]
